export const seedApps = [
  {
    id: "app_weixin",
    name: "微信",
    aliases: ["微信", "wechat", "wx", "微心", "weixin"],
    icon: "微",
    officialSite: "https://weixin.qq.com",
    android: "https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_download_list&platform=android",
    ios: "https://apps.apple.com/cn/app/wechat/id414478124",
    valid: true,
    weight: 100,
    updatedAt: "2026-06-23T00:00:00.000Z",
  },
  {
    id: "app_dingtalk",
    name: "钉钉",
    aliases: ["钉钉", "dingtalk", "dingding", "丁丁"],
    icon: "钉",
    officialSite: "https://www.dingtalk.com",
    android: "https://page.dingtalk.com/wow/dingtalk/act/download",
    ios: "https://apps.apple.com/cn/app/dingtalk/id930368978",
    valid: true,
    weight: 94,
    updatedAt: "2026-06-23T00:00:00.000Z",
  },
  {
    id: "app_feishu",
    name: "飞书",
    aliases: ["飞书", "feishu", "larksuite", "lark"],
    icon: "飞",
    officialSite: "https://www.feishu.cn",
    android: "https://www.feishu.cn/download",
    ios: "https://apps.apple.com/cn/app/lark/id1160796444",
    valid: true,
    weight: 90,
    updatedAt: "2026-06-23T00:00:00.000Z",
  },
  {
    id: "app_wecom",
    name: "企业微信",
    aliases: ["企业微信", "企微", "wecom", "wxwork"],
    icon: "企",
    officialSite: "https://work.weixin.qq.com",
    android: "https://work.weixin.qq.com/#indexDownload",
    ios: "https://apps.apple.com/cn/app/wecom/id1189898970",
    valid: true,
    weight: 88,
    updatedAt: "2026-06-23T00:00:00.000Z",
  },
  {
    id: "app_tencent_meeting",
    name: "腾讯会议",
    aliases: ["腾讯会议", "会议", "tencent meeting", "voov"],
    icon: "会",
    officialSite: "https://meeting.tencent.com",
    android: "https://meeting.tencent.com/download",
    ios: "https://apps.apple.com/cn/app/tencent-meeting/id1484048379",
    valid: true,
    weight: 84,
    updatedAt: "2026-06-23T00:00:00.000Z",
  },
  {
    id: "app_invalid_demo",
    name: "小众失效示例",
    aliases: ["失效", "全部失效", "invalid"],
    icon: "失",
    officialSite: "https://official.example.invalid",
    android: "https://download.example.invalid/android",
    ios: "",
    valid: false,
    weight: 60,
    updatedAt: "2026-06-23T00:00:00.000Z",
  },
];
