const seedUpdatedAt = "2026-06-30T00:00:00.000Z";

export const seedApps = [
  {
    id: "app_weixin",
    name: "微信",
    aliases: ["微信", "wechat", "wx", "微心", "weixin"],
    icon: "微",
    officialSite: "https://weixin.qq.com",
    android: "https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_download_list&platform=android",
    ios: "https://apps.apple.com/cn/app/wechat/id414478124",
    officialDomain: "weixin.qq.com",
    valid: true,
    weight: 100,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_dingtalk",
    name: "钉钉",
    aliases: ["钉钉", "dingtalk", "dingding", "丁丁"],
    icon: "钉",
    officialSite: "https://www.dingtalk.com",
    android: "https://page.dingtalk.com/wow/dingtalk/act/download",
    ios: "https://apps.apple.com/cn/app/dingtalk/id930368978",
    officialDomain: "dingtalk.com",
    valid: true,
    weight: 99,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_feishu",
    name: "飞书",
    aliases: ["飞书", "feishu", "larksuite", "lark"],
    icon: "飞",
    officialSite: "https://www.feishu.cn",
    android: "https://www.feishu.cn/download",
    ios: "https://apps.apple.com/cn/app/lark/id1160796444",
    officialDomain: "feishu.cn",
    valid: true,
    weight: 98,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_wecom",
    name: "企业微信",
    aliases: ["企业微信", "企微", "wecom", "wxwork"],
    icon: "企",
    officialSite: "https://work.weixin.qq.com",
    android: "https://work.weixin.qq.com/#indexDownload",
    ios: "https://apps.apple.com/cn/app/wecom/id1189898970",
    officialDomain: "weixin.qq.com",
    valid: true,
    weight: 97,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_tencent_meeting",
    name: "腾讯会议",
    aliases: ["腾讯会议", "会议", "tencent meeting", "voov"],
    icon: "会",
    officialSite: "https://meeting.tencent.com",
    android: "https://meeting.tencent.com/download",
    ios: "https://apps.apple.com/cn/app/tencent-meeting/id1484048379",
    officialDomain: "tencent.com",
    valid: true,
    weight: 96,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_qq",
    name: "QQ",
    aliases: ["QQ", "腾讯QQ", "qq", "imqq"],
    icon: "Q",
    officialSite: "https://im.qq.com",
    android: "https://im.qq.com/download",
    ios: "",
    officialDomain: "qq.com",
    valid: true,
    weight: 95,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_alipay",
    name: "支付宝",
    aliases: ["支付宝", "alipay", "蚂蚁支付"],
    icon: "支",
    officialSite: "https://www.alipay.com",
    android: "",
    ios: "",
    officialDomain: "alipay.com",
    valid: true,
    weight: 94,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_taobao",
    name: "淘宝",
    aliases: ["淘宝", "手机淘宝", "taobao"],
    icon: "淘",
    officialSite: "https://www.taobao.com",
    android: "",
    ios: "",
    officialDomain: "taobao.com",
    valid: true,
    weight: 93,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_tmall",
    name: "天猫",
    aliases: ["天猫", "tmall", "天猫商城"],
    icon: "天",
    officialSite: "https://www.tmall.com",
    android: "",
    ios: "",
    officialDomain: "tmall.com",
    valid: true,
    weight: 92,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_jd",
    name: "京东",
    aliases: ["京东", "jd", "京东商城"],
    icon: "京",
    officialSite: "https://www.jd.com",
    android: "",
    ios: "",
    officialDomain: "jd.com",
    valid: true,
    weight: 91,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_pinduoduo",
    name: "拼多多",
    aliases: ["拼多多", "pinduoduo", "pdd"],
    icon: "拼",
    officialSite: "https://www.pinduoduo.com",
    android: "",
    ios: "",
    officialDomain: "pinduoduo.com;yangkeduo.com",
    valid: true,
    weight: 90,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_meituan",
    name: "美团",
    aliases: ["美团", "meituan", "美团外卖"],
    icon: "美",
    officialSite: "https://www.meituan.com",
    android: "",
    ios: "",
    officialDomain: "meituan.com",
    valid: true,
    weight: 89,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_ele_me",
    name: "饿了么",
    aliases: ["饿了么", "eleme", "ele.me"],
    icon: "饿",
    officialSite: "https://www.ele.me",
    android: "",
    ios: "",
    officialDomain: "ele.me",
    valid: true,
    weight: 88,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_amap",
    name: "高德地图",
    aliases: ["高德地图", "高德", "amap"],
    icon: "高",
    officialSite: "https://www.amap.com",
    android: "",
    ios: "",
    officialDomain: "amap.com",
    valid: true,
    weight: 87,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_baidu_map",
    name: "百度地图",
    aliases: ["百度地图", "baidu map", "地图"],
    icon: "百",
    officialSite: "https://map.baidu.com",
    android: "",
    ios: "",
    officialDomain: "baidu.com",
    valid: true,
    weight: 86,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_didi",
    name: "滴滴出行",
    aliases: ["滴滴", "滴滴出行", "didi"],
    icon: "滴",
    officialSite: "https://www.didiglobal.com",
    android: "",
    ios: "",
    officialDomain: "didiglobal.com",
    valid: true,
    weight: 85,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_ctrip",
    name: "携程旅行",
    aliases: ["携程", "携程旅行", "ctrip", "trip.com"],
    icon: "携",
    officialSite: "https://www.ctrip.com",
    android: "",
    ios: "",
    officialDomain: "ctrip.com",
    valid: true,
    weight: 84,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_qunar",
    name: "去哪儿旅行",
    aliases: ["去哪儿", "去哪儿旅行", "qunar"],
    icon: "去",
    officialSite: "https://www.qunar.com",
    android: "",
    ios: "",
    officialDomain: "qunar.com",
    valid: true,
    weight: 83,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_ly",
    name: "同程旅行",
    aliases: ["同程", "同程旅行", "ly.com"],
    icon: "同",
    officialSite: "https://www.ly.com",
    android: "",
    ios: "",
    officialDomain: "ly.com",
    valid: true,
    weight: 82,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_12306",
    name: "铁路12306",
    aliases: ["12306", "铁路12306", "中国铁路12306"],
    icon: "铁",
    officialSite: "https://www.12306.cn",
    android: "",
    ios: "",
    officialDomain: "12306.cn",
    valid: true,
    weight: 81,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_xiaohongshu",
    name: "小红书",
    aliases: ["小红书", "red", "rednote", "xiaohongshu"],
    icon: "红",
    officialSite: "https://www.xiaohongshu.com",
    android: "",
    ios: "",
    officialDomain: "xiaohongshu.com",
    valid: true,
    weight: 80,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_weibo",
    name: "微博",
    aliases: ["微博", "新浪微博", "weibo"],
    icon: "博",
    officialSite: "https://weibo.com",
    android: "",
    ios: "",
    officialDomain: "weibo.com",
    valid: true,
    weight: 79,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_zhihu",
    name: "知乎",
    aliases: ["知乎", "zhihu"],
    icon: "知",
    officialSite: "https://www.zhihu.com",
    android: "",
    ios: "",
    officialDomain: "zhihu.com",
    valid: true,
    weight: 78,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_bilibili",
    name: "哔哩哔哩",
    aliases: ["哔哩哔哩", "B站", "bilibili"],
    icon: "哔",
    officialSite: "https://www.bilibili.com",
    android: "",
    ios: "",
    officialDomain: "bilibili.com",
    valid: true,
    weight: 77,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_douyin",
    name: "抖音",
    aliases: ["抖音", "douyin"],
    icon: "抖",
    officialSite: "https://www.douyin.com",
    android: "",
    ios: "",
    officialDomain: "douyin.com",
    valid: true,
    weight: 76,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_kuaishou",
    name: "快手",
    aliases: ["快手", "kuaishou", "ks"],
    icon: "快",
    officialSite: "https://www.kuaishou.com",
    android: "",
    ios: "",
    officialDomain: "kuaishou.com",
    valid: true,
    weight: 75,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_ixigua",
    name: "西瓜视频",
    aliases: ["西瓜视频", "西瓜", "ixigua"],
    icon: "西",
    officialSite: "https://www.ixigua.com",
    android: "",
    ios: "",
    officialDomain: "ixigua.com",
    valid: true,
    weight: 74,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_toutiao",
    name: "今日头条",
    aliases: ["今日头条", "头条", "toutiao"],
    icon: "头",
    officialSite: "https://www.toutiao.com",
    android: "",
    ios: "",
    officialDomain: "toutiao.com",
    valid: true,
    weight: 73,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_tencent_video",
    name: "腾讯视频",
    aliases: ["腾讯视频", "腾讯视频APP", "v.qq.com"],
    icon: "腾",
    officialSite: "https://v.qq.com",
    android: "",
    ios: "",
    officialDomain: "qq.com",
    valid: true,
    weight: 72,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_iqiyi",
    name: "爱奇艺",
    aliases: ["爱奇艺", "iqiyi"],
    icon: "爱",
    officialSite: "https://www.iqiyi.com",
    android: "",
    ios: "",
    officialDomain: "iqiyi.com",
    valid: true,
    weight: 71,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_youku",
    name: "优酷",
    aliases: ["优酷", "youku"],
    icon: "优",
    officialSite: "https://www.youku.com",
    android: "",
    ios: "",
    officialDomain: "youku.com",
    valid: true,
    weight: 70,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_mgtv",
    name: "芒果TV",
    aliases: ["芒果TV", "芒果", "mgtv"],
    icon: "芒",
    officialSite: "https://www.mgtv.com",
    android: "",
    ios: "",
    officialDomain: "mgtv.com",
    valid: true,
    weight: 69,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_netease_music",
    name: "网易云音乐",
    aliases: ["网易云音乐", "网易云", "netease music", "music.163"],
    icon: "云",
    officialSite: "https://music.163.com",
    android: "",
    ios: "",
    officialDomain: "163.com",
    valid: true,
    weight: 68,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_qq_music",
    name: "QQ音乐",
    aliases: ["QQ音乐", "qq music", "y.qq.com"],
    icon: "音",
    officialSite: "https://y.qq.com",
    android: "",
    ios: "",
    officialDomain: "qq.com",
    valid: true,
    weight: 67,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_kugou",
    name: "酷狗音乐",
    aliases: ["酷狗音乐", "酷狗", "kugou"],
    icon: "酷",
    officialSite: "https://www.kugou.com",
    android: "",
    ios: "",
    officialDomain: "kugou.com",
    valid: true,
    weight: 66,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_ximalaya",
    name: "喜马拉雅",
    aliases: ["喜马拉雅", "ximalaya"],
    icon: "喜",
    officialSite: "https://www.ximalaya.com",
    android: "",
    ios: "",
    officialDomain: "ximalaya.com",
    valid: true,
    weight: 65,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_douban",
    name: "豆瓣",
    aliases: ["豆瓣", "douban"],
    icon: "豆",
    officialSite: "https://www.douban.com",
    android: "",
    ios: "",
    officialDomain: "douban.com",
    valid: true,
    weight: 64,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_baidu_pan",
    name: "百度网盘",
    aliases: ["百度网盘", "百度云", "pan.baidu.com"],
    icon: "盘",
    officialSite: "https://pan.baidu.com",
    android: "",
    ios: "",
    officialDomain: "baidu.com",
    valid: true,
    weight: 63,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_wps",
    name: "WPS Office",
    aliases: ["WPS", "WPS Office", "金山文档", "wps office"],
    icon: "W",
    officialSite: "https://www.wps.cn",
    android: "",
    ios: "",
    officialDomain: "wps.cn",
    valid: true,
    weight: 62,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_quark",
    name: "夸克",
    aliases: ["夸克", "夸克浏览器", "quark"],
    icon: "夸",
    officialSite: "https://www.quark.cn",
    android: "",
    ios: "",
    officialDomain: "quark.cn",
    valid: true,
    weight: 61,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_uc",
    name: "UC浏览器",
    aliases: ["UC浏览器", "UC", "uc browser"],
    icon: "U",
    officialSite: "https://www.uc.cn",
    android: "",
    ios: "",
    officialDomain: "uc.cn",
    valid: true,
    weight: 60,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_sogou_input",
    name: "搜狗输入法",
    aliases: ["搜狗输入法", "搜狗", "sogou pinyin"],
    icon: "搜",
    officialSite: "https://pinyin.sogou.com",
    android: "",
    ios: "",
    officialDomain: "sogou.com",
    valid: true,
    weight: 59,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_iflytek_input",
    name: "讯飞输入法",
    aliases: ["讯飞输入法", "讯飞", "iflytek"],
    icon: "讯",
    officialSite: "https://srf.xunfei.cn",
    android: "",
    ios: "",
    officialDomain: "xunfei.cn",
    valid: true,
    weight: 58,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_youdao_dict",
    name: "有道词典",
    aliases: ["有道词典", "网易有道词典", "youdao"],
    icon: "有",
    officialSite: "https://dict.youdao.com",
    android: "",
    ios: "",
    officialDomain: "youdao.com",
    valid: true,
    weight: 57,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_zuoyebang",
    name: "作业帮",
    aliases: ["作业帮", "zuoyebang"],
    icon: "作",
    officialSite: "https://www.zybang.com",
    android: "",
    ios: "",
    officialDomain: "zybang.com;zuoyebang.com",
    valid: true,
    weight: 56,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_yuanfudao",
    name: "猿辅导",
    aliases: ["猿辅导", "yuanfudao"],
    icon: "猿",
    officialSite: "https://www.yuanfudao.com",
    android: "",
    ios: "",
    officialDomain: "yuanfudao.com",
    valid: true,
    weight: 55,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_dewu",
    name: "得物",
    aliases: ["得物", "毒", "dewu"],
    icon: "得",
    officialSite: "https://www.dewu.com",
    android: "",
    ios: "",
    officialDomain: "dewu.com",
    valid: true,
    weight: 54,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_goofish",
    name: "闲鱼",
    aliases: ["闲鱼", "咸鱼", "goofish"],
    icon: "闲",
    officialSite: "https://www.goofish.com",
    android: "",
    ios: "",
    officialDomain: "goofish.com",
    valid: true,
    weight: 53,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_58",
    name: "58同城",
    aliases: ["58同城", "58", "58.com"],
    icon: "5",
    officialSite: "https://www.58.com",
    android: "",
    ios: "",
    officialDomain: "58.com",
    valid: true,
    weight: 52,
    updatedAt: seedUpdatedAt,
  },
  {
    id: "app_zhipin",
    name: "BOSS直聘",
    aliases: ["BOSS直聘", "boss直聘", "zhipin"],
    icon: "B",
    officialSite: "https://www.zhipin.com",
    android: "",
    ios: "",
    officialDomain: "zhipin.com",
    valid: true,
    weight: 51,
    updatedAt: seedUpdatedAt,
  },
];
